import type { Metadata } from "next";
import "../globals.css";

import { Layout } from "@/layout";
import { NextUIProvider } from "@/providers/NextUI";
import ActiveSectionContextProvider from "@/providers/ActiveSection";
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata: Metadata = {
  title: "Bishkek Marathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NextUIProvider>
            <ActiveSectionContextProvider>
              <Layout>{children}</Layout>
            </ActiveSectionContextProvider>
          </NextUIProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
